title: Aristotle
description: "Cursor for game dev. Less time fighting your code, more time making your game. And no AI assets, ever."
url: "https://aristotle.games"
baseurl: ""

# Build settings
markdown: kramdown
permalink: /blog/:year/:month/:day/:title/

# Exclude from build
exclude:
  - README.md
  - Gemfile
  - Gemfile.lock
